USE [Helperland1]
Go

/* UNIQUE KEY*/

ALTER TABLE Customer
ADD CONSTRAINT UC_Customer_Email UNIQUE (Email)

ALTER TABLE Service_Provider
ADD CONSTRAINT UC_SP_Email UNIQUE (Email)

ALTER TABLE Admin_Detail
ADD CONSTRAINT UC_AD_Username UNIQUE (Username)

ALTER TABLE Info_Contact
ADD CONSTRAINT UC_IC_CID UNIQUE (Cont_Id)

ALTER TABLE Info_Contact
ADD CONSTRAINT UC_IC_Email UNIQUE (Email)

ALTER TABLE Info_NewsLetter
ADD CONSTRAINT UC_IN_NID UNIQUE (News_Id)

/*FOREIGN KEY*/

ALTER TABLE Customer
ADD CONSTRAINT FK_Customer_RID
FOREIGN KEY (Role_Id) REFERENCES Role_Detail(Role_Id)

ALTER TABLE Service_Provider
ADD CONSTRAINT FK_SP_RID
FOREIGN KEY (Role_Id) REFERENCES Role_Detail(Role_Id)

ALTER TABLE Cust_Address
ADD CONSTRAINT FK_CA_CID
FOREIGN KEY (Cust_Id) REFERENCES Customer(Cust_Id)

ALTER TABLE [Service]
ADD CONSTRAINT FK_Service_SPID
FOREIGN KEY (Sp_Id) REFERENCES Service_Provider(Sp_Id)

ALTER TABLE [Service]
ADD CONSTRAINT FK_Service_CID
FOREIGN KEY (Cust_Id) REFERENCES Customer(Cust_Id)

ALTER TABLE Fav_SP
ADD CONSTRAINT FK_FS_SPID
FOREIGN KEY (Sp_Id) REFERENCES Service_Provider(Sp_Id)

ALTER TABLE Fav_SP
ADD CONSTRAINT FK_FS_CID
FOREIGN KEY (Cust_Id) REFERENCES Customer(Cust_Id)

ALTER TABLE Rate_SP
ADD CONSTRAINT FK_RS_SPID
FOREIGN KEY (Sp_Id) REFERENCES Service_Provider(Sp_Id)

ALTER TABLE Rate_SP
ADD CONSTRAINT FK_RS_CID
FOREIGN KEY (Cust_Id) REFERENCES Customer(Cust_Id)

ALTER TABLE Rate_SP
ADD CONSTRAINT FK_RS_SID
FOREIGN KEY (Serv_Id) REFERENCES [Service](Serv_Id)

ALTER TABLE Block_Cust
ADD CONSTRAINT FK_BC_SPID
FOREIGN KEY (Sp_Id) REFERENCES Service_Provider(Sp_Id)

ALTER TABLE Block_Cust
ADD CONSTRAINT FK_BC_CID
FOREIGN KEY (Cust_Id) REFERENCES Customer(Cust_Id)
